### ISSUE TITLE
How I managed to break lift

### ISSUE THREAD

**Issue by MikeGold** [croxis/Lift#128]
I'm using the most recent lift version 51.
- I had a lift 3x3 blocks.
- I was standing on the lift while the horse was standing only halfway on it and half on the ground.
- I have started a lift by clicking button.
- Me and horse went up.
- Horse got stuck near to the 2nd floor and the lift started shaking up and down.
- Horse died crushed
- Lift didn't stopped shaking I couldn't leave it.
- I have relogged, the glass from 2nd floor was gone and even after fixing lift was not working
- the signs of the lift were not destructible (even for admin), only worldedit tool could destroy them.
- rebuilding lift, adding extra floor didn't helped and lift was not working at all.
- After server restart lift came back to normal and worked perfectly.

**Comment by croxis** [comment]
I have ideas on how to fix.

Reminders for me:

Allow ops and permission node for entering lift and cancel command.

Verify code for horses

**Comment by psirusa** [comment]
I can confirm this issue, and I believe it may happen if any entity dies while being transported by the lift.  With me it was a chicken that got stuck in the ceiling (lift shaft was not exact cut).  I went up 40 blocks, and was stuck in mid-air.  On relog I fell to the floor that I started from (and died >.<), and the elevator refused to work until a server restart.

**Comment by trainphreak** [comment]
@psirusa is correct. If any entity dies or gets obstructed while being lifted, the elevator will not stop trying to lift the other entities. This is still an issue in v52.

**Comment by croxis** [comment]
Yah it was a situation I never was able to solve, I'm not sure what changes
happen to the entity so I'm not sure how to manage it. I haven't touched
the code in a while and I probably wont be able to get to it until spring
break (joys of being a teacher)

On Sun, Feb 28, 2016 at 1:02 PM, trainphreak <notifications@github.com>
wrote:

> @psirusa <https://github.com/psirusa> is correct. If any entity dies or
> gets obstructed while being lifted, the elevator will not stop trying to
> lift the other entities. This is still an issue in v52.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croxis/Lift/issues/128#issuecomment-189946014>.
>



-- 
- David - Proud to be saving the world since 1984

**Comment by croxis** [comment]
I have code that cleans up the passenger list if the entity dies. Willing to reopen if this continues version 59 on.
