### ISSUE TITLE
Playere able to fly after used lify

### ISSUE THREAD

**Issue by xion87** [croxis/Lift#129]
I noticed now player after lift use they can fly around....

**Comment by croxis** [comment]
Post lift config, lift version, and bukkit/spiggot version

On Sat, Feb 28, 2015 at 2:53 PM, xion87 <notifications@github.com> wrote:

> I noticed now player after lift use they can fly around....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croxis/Lift/issues/129>.
>



-- 
- David - Proud to be saving the world since 1984

**Comment by xion87** [comment]
Config: http://pastebin.com/Uyz1F25N
Lift version 51
Spigot version: git-Spigot-35348a5-ee6d0fa (MC: 1.8) (Implementing API version 1.8-R0.1-SNAPSHOT)

**Comment by croxis** [comment]
I can not duplicate using 1.8.3 and lift 52

**Comment by xion87** [comment]
this issue seem fixed with 1.8.3
