### ISSUE TITLE
Lift stopped working and error message appeared in Console

### ISSUE THREAD

**Issue by Jawakotb** [croxis/Lift#130]
Just installed the plugin and after making a few lifts, they randomly stopped working.  (Glass floor unable to break or glass floor missing.  Some peeps found a console message saying 'you're already in a lift, please relog."  

This error shows up on Console:  
[22:04:47] [Server thread/WARN]: [Lift] Task #118 for Lift v52 generated an exception
java.lang.NullPointerException

My server host is running 1.8 of java, hope that is not the cause.

Thanks!

**Comment by croxis** [comment]
Java 1.8 should be fine. It is what I use to test with. I need more of a traceback to find out what is returning the exception.

**Comment by Jawakotb** [comment]
Croxis,
  What do you need from me for the 'traceback'?  Also, one of my server admins says he say the 'clearlagg' plugin mess with one of the 'lifts' during an automated clearlagg event. (It clears all non-whitelisted entities from the server to reduce server overhead)

Does the lift plugin turn the glass blocks into entities during operation by chance?

Thanks for the feedback and please do let me know what I can do to help make this plugin great as the folks on my server love it!

**Comment by croxis** [comment]
For the traceback/stacktrace I need to see what line of code is returning the null object. It may be hiding in your logs.

Blocks are not turned into entities while the lift is in motion. However the lift does store a list of entities that are in an active lift. If the entity is deleted by a plugin while in a lift the lift still thinks there is an entity there when there isn't anymore. I will have to think of a graceful solution.

**Comment by Jawakotb** [comment]
I will review the logs to see if I can pull anything out.

Thanks!

**Comment by croxis** [comment]
Closing for lack on information.. that is probably very out of date now anyways,
