### ISSUE TITLE
Lifts turning into deathtraps

### ISSUE THREAD

**Issue by DragaoNimhe** [croxis/Lift#132]
Hey, I'm a mod on a fairly active server that uses and loves your lift plugin. Our players and staff have integrated your lifts into almost every build we make, but there's one issue that is literally killing us. When someone is using the lift, and someone else approaches the lift, it goes from an elevator to a fall to your death. I have a lift at my high-traffic town spawn. Even though I have signs warning people to wait for the glass to reappear, someone dies at my town spawn, on average, twice a day. Is there any fix for this?

**Comment by croxis** [comment]
Is can enter set to false? Post the lift config and I can double check

**Comment by DragaoNimhe** [comment]
Just spoke with the owner, he says it is set to false.

**Comment by CathalCraft** [comment]
I'm the owner. The config is:
maxLiftArea: 16
maxHeight: 256
debug: false
autoPlace: false
preventEntry: false
preventLeave: true
checkFloor: true
liftMobs: false
floorBlocks:
- GLASS
- STAINED_GLASS
redstone: false
baseBlockSpeeds:
  IRON_BLOCK: 0.5
STRING_oneFloor: There is only one floor.
STRING_currentFloor: 'Current Floor:'
STRING_dest: 'Floor:'
STRING_cantEnter: Can't enter elevator in use.
STRING_cantLeave: Can't leave elevator in use.
checkGlass: true
collectStats: true

**Comment by croxis** [comment]
Setting preventEntry to true will solve your issues.
