### ISSUE TITLE
Elevator Breaking + Glass Self-Deleting

### ISSUE THREAD

**Issue by Matt7811** [croxis/Lift#134]
Hi, I am a staff member on a server that is using (I believe) the most recent version of Lift on Minecraft 1.8.8.  I can't give you any console reports but I can describe the problem at hand in detail.

I personally have a 14 floor elevator that goes from bedrock to the height limit.  It is in a custom world, in a mountain.  On the 4th floor I was mining out some cobblestone and I put the cobblestone I had into the elevator (going to the 11th floor) and got into the elevator with it.  I got to the top and I was stuck, I look down and see the cobblestone falling, glitching back up, falling, glitching back up, over and over again.  Because I was stuck I relogged and when I came back online, the glass was gone and when I tried to fix it the elevator was completely broken.  I've experienced this problem before and it has only once fixed itself.  Possibly due to a server restart?  

Please help me with this problem.  If possible, please email jbkuehlw@hotmail.com with the problem.

Thanks.  :-D

**Comment by croxis** [comment]
A server restart should fix the problem. You will just have to go through
your elevator and verify all the blocks are fine
