### ISSUE TITLE
Aaaah console spam

### ISSUE THREAD

**Issue by DannyPokemon** [croxis/Lift#136]
03.03 10:41:24 [Server] INFO java.lang.NullPointerException
03.03 10:41:24 [Server] WARN Task #27 for Lift v52 generated an exception
03.03 10:41:23 [Server] INFO java.lang.NullPointerException
03.03 10:41:23 [Server] WARN Task #27 for Lift v52 generated an exception
03.03 10:41:23 [Server] INFO java.lang.NullPointerException
every second. annoying. acts like my server is broke. worked fine be4 but i installed backup and this is what happens.

**Comment by croxis** [comment]
Should fix with a server restart. I suspect it is a bug with how the lift
handles other objects.

**Comment by DannyPokemon** [comment]
Sorry had to wait for all players to finally quit. Yes a restart fixed it done.well #Blame1.8 it's done nothing but break Java developers plugins :(
