### ISSUE TITLE
Need a way to set floor name when carpet is placed

### ISSUE THREAD

**Issue by hit1205** [croxis/Lift#138]
The optional sign for floor name required to be placed under the button now, so if there are carpets on the floor, I cannot set floor name anymore. Is there any possible to add a feature to set floor name and place carpets in the same time? How about let the optional sign could be placed above the required sign?

**Comment by croxis** [comment]
Not easily. I could put it on the top sign instead.

On Sun, Jun 12, 2016 at 5:12 AM, Huang Yaoting <notifications@github.com>
wrote:

> The optional sign for floor name required to be placed under the button
> now, so if there are carpets on the floor, I cannot set floor name anymore.
> Is there any possible to add a feature to set floor name and place carpets
> in the same time? How about let the optional sign could be placed above the
> required sign?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/croxis/Lift/issues/138>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAHa9xygc-Lp0gDkTeny6CNojKvlj1e1ks5qK_eogaJpZM4Izxwb>
> .
>



-- 
- David - Proud to be saving the world since 1984

**Comment by croxis** [comment]
Fixed with sign update in v 59
