### ISSUE TITLE
NCP Incompatibility - Lift causes player fall damage.

### ISSUE THREAD

**Issue by bc-hill** [croxis/Lift#151]
As reported on the Spigot resource discussion [thread](https://www.spigotmc.org/threads/lift.53836/page-3), and confirmed by me, players take damage after riding down elevator. This occurs regardless of speed.
Spigot 1.12.2

**Comment by croxis** [comment]
Is this solo or with multiple passengers

**Comment by bc-hill** [comment]
This is solo. I have not yet tested with multiple passengers.
Thank you.

**Comment by bc-hill** [comment]
Confirming that it occurs with two passengers.  Though, I am unable to accurately predict who will take damage.  Sometimes one player will survive, sometimes both players take damage.

**Comment by croxis** [comment]
I still can't duplicate it, can you send me a list of plugins?

**Comment by bc-hill** [comment]
I realized that I am using one of the popular newer configs,[ this one](https://www.spigotmc.org/threads/nocheatplus-config-optimized-and-free.158041/).  
Unsure if that is making any difference.

**Comment by bc-hill** [comment]
I tried the above version of NoCheatPlus with it's default config, and couldn't even ride the elevator.
```
18-04-10 09:03:24 [INFO] username failed SurvivalFly: tried to move: -233.97, 90.06, 152.95 -> -233.97, 89.56, 152.95, d=0.50 (data_reset+vdistrel). VL 105.
18-04-10 09:03:24 [INFO] username failed SurvivalFly: tried to move: -233.97, 90.06, 152.95 -> -233.97, 88.99, 152.95, d=1.07 (data_reset+vdistrel). VL 462.
18-04-10 09:03:27 [INFO] username failed SurvivalFly: tried to move: -233.97, 90.06, 152.95 -> -233.97, 89.56, 152.95, d=0.50 (data_reset+vdistrel). VL 1519.
18-04-10 09:03:27 [INFO] (CONSOLE) Kicked username: Kicked for flying (or related)
```

**Comment by croxis** [comment]
Should be fixed
