### ISSUE TITLE
Compile error accessing private property of LiftSign

### ISSUE THREAD

**Issue by LeoQuote** [croxis/Lift#157]
at https://github.com/croxis/Lift/blob/master/src/main/java/net/croxis/plugins/lift/SpongeLiftRedstoneListener.java#L98 accessing private property of LiftSign

I changed the property to public and works fine https://github.com/croxis/Lift/blob/master/src/main/java/net/croxis/plugins/lift/LiftSign.java#L45

But I wonder if there's any side effect.... did you experienced this?

**Comment by croxis** [comment]
I had it set to public, but now that I'm trying to update the sign syntax in a somewhat safe way behind the LiftSign class I switched it to private. I forgot to push my recent changes which should fix the problem. Redo the pull request if I didn't. I hope to get a new version out soon.

**Comment by LeoQuote** [comment]
sure thing, thanks for your contribution, looking forward to the next version!
