### ISSUE TITLE
Getting random numbers in console

### ISSUE THREAD

**Issue by RazihelYT** [croxis/Lift#160]
Hey there, Whenever someone uses a lift button on the server, my server console gets the number 2 outputted 3 times. Ive tried disabling metrics and other checks, but it still persists. Any help is appreciated!

**Comment by croxis** [comment]
What build/version?

**Comment by RazihelYT** [comment]
Its the most recent one actually

**Comment by croxis** [comment]
I honestly can't find it (unless I already removed it). Do you know what is happening when it prints?

**Comment by RazihelYT** [comment]
Its only when a player clicked the button to activate the elevator, Happens when player is going up or down, and is not floor specific.

**Comment by croxis** [comment]
Ok. I think a had already removed it for v60 which I hope for next weekend (famous last words). I'll leave this open in case it continues to happen.

**Comment by RazihelYT** [comment]
Would you mind if I test it out on my server? I have a lot of free-time on my hands and would be glad to test it out and see if the issue was resolved.

**Comment by croxis** [comment]
If you can you can build from this repo. My current code is a bit broken as
I am adding support for mounted horses.

**Comment by RazihelYT** [comment]
Noticed right away after importing Spigot and CraftBukkit 1.14, that the Material.WALL_SIGN is an invalid material, I've made a pull request with fixes related to the issues.

**Comment by RazihelYT** [comment]
Noticed an error in 59, The coordinates are for the 2nd floor with the glass blocks, and I think it's checking for redstone blocks under the glass?
07.05 01:24:39 [Server] Server thread/INFO [Lift] WARNING: Unable to get sign for redstone pulse.
07.05 01:24:39 [Server] Server thread/INFO [Lift] Sign coords: Location{world=CraftWorld{name=Gallifrey},x=-247.0,y=92.0,z=-2.0,pitch=0.0,yaw=0.0}
07.05 01:24:39 [Server] Server thread/INFO [Lift] Sign material: OAK_WALL_SIGN

**Comment by croxis** [comment]
Fixed! I think. I'm not getting the error any more either
