### ISSUE TITLE
Config resets on reload/restart

### ISSUE THREAD

**Issue by MrCookiePrincess** [croxis/Lift#171]
I don't know what I'm doing wrong I only changed line 25 to "  IRON_BLOCK: 1.0" because the elevator on my skyscraper takes so long but when I resarted the server it was back to 0.5
I also tried to change the 28th line to "STRING_dest: §0Dest" but again after a restart its back to the original.

I also tried more stuff but it all ends up being resetted

Regards. Cookie

**Comment by croxis** [comment]
Does config.yaml stay the same?

On Wed, Aug 28, 2019 at 7:12 AM MrCookiePrincess
<notifications@github.com> wrote:
>
> I don't know what I'm doing wrong I only changed line 25 to " IRON_BLOCK: 1.0" because the elevator on my skyscraper takes so long but when I resarted the server it was back to 0.5
> I also tried to change the 28th line to "STRING_dest: §0Dest" but again after a restart its back to the original.
>
> I also tried more stuff but it all ends up being resetted
>
> Regards. Cookie
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
- David - Proud to be saving the world since 1984

**Comment by kikelkik** [comment]
I'm facing the same problem. E.g. changing to debug: true and then /lift changes nothing and reverts the config.yaml so my changes are undid.

**Comment by croxis** [comment]
I've never fully understood the config API of bukkit. I'll take a look after I'm not under threat of evacuation from these forest fires.

**Comment by kikelkik** [comment]
Fixed in [Lift 69](https://dev.bukkit.org/projects/lift/files/3093588)
