### ISSUE TITLE
1.14.4 Support

### ISSUE THREAD

**Issue by GiraffeCubed** [croxis/Lift#173]
Currently Lift does not work in 1.14.4. This appears to be the final version of 1.14 so it would be fantastic to have Lift updated to support it. Is this planned?

Have been using this plugin for years, it beats other lift/elevator plugins by a long shot! Can't wait to have it back on my server.

**Comment by TheoRetisch1** [comment]
I have the same problem and would be very happy about an update :)

**Comment by croxis** [comment]
Done

**Comment by TheoRetisch1** [comment]
Thank you!
