### ISSUE TITLE
1.15 Start-up Error

### ISSUE THREAD

**Issue by TheoRetisch1** [croxis/Lift#174]
Unfortunately Lift does not start in 1.15.1 :/
Error: https://pastebin.com/zJRgFTLC

Lift - 62
Paper 1.15.1 - 29

**Comment by croxis** [comment]
Log says it is an older version of lift

**Comment by TheoRetisch1** [comment]
Thanks for the update! It now works using version 63 :)

**Comment by TheoRetisch1** [comment]
With version 8.6.22.1 we are now back to the original stage. If the signs are not placed at eye level, you end up in the upper/lower floor. The examples from the original description are valid again. This happens permission independent in all three gamemodes survival, specator and creative. The bug occurs in version 1.13 as well as in version 1.15.
Should I open a new ticket or could you reopen this one for the sake of simplicity?
