### ISSUE TITLE
Config reset - floor blocks

### ISSUE THREAD

**Issue by corwinbass** [croxis/Lift#175]
no matter what, even when default config is used, it always changes floor blocks to only glass and white stained glass, not allowing other glass types.

original config contains this.
`floorBlocks:
- GLASS
- "*_GLASS"`

when server loads plugin, it prints in console 
`[Lift] Floor material added: GLASS
[Lift] Floor material added: WHITE_STAINED_GLASS` 
and same glass types are saved in config, overwriting the *_GLASS value

if i shutdown server and change config back, it has same result, upon server start it adds GLASS and WHITE_STAINED_GLASS only

**Comment by corwinbass** [comment]
updated to ver 63 and it works now. i should have tried that first

**Comment by croxis** [comment]
Yay! Glad it does
