### ISSUE TITLE
[Question / Request] Is it possible to change the text color on signs?

### ISSUE THREAD

**Issue by derMiepz** [croxis/Lift#176]
Can you change the color of the text? Editing the text is really easy, but with the newer MC version you get darker signs and it can be hard to read black / dark blue on dark oak or spruce signs.
The config has this string `STRING_dest: ยง1Ziel`, but I don't know how to interpret `ยง1`. Something like the normal color codes would be easier to use. ^^
![](https://i.imgur.com/nVPys4Z.png)

**Comment by croxis** [comment]
I'll need to look at how color is done now. Those symbols are the old
fashioned way of setting color in the game.

**Comment by derMiepz** [comment]
It'd be really nice and this shouldn't be to big of a hassle.

**Comment by croxis** [comment]
I'm not going to change it right now. It looks like it is still the standard: https://minecraft.gamepedia.com/Formatting_codes

**Comment by derMiepz** [comment]
I don't see `ยง` anywhere as a formatting code so not sure how this is standard.

**Comment by croxis** [comment]
Please review the link I posted. If it is showing up as a different character that is your editor's Unicode issue.
