### ISSUE TITLE
Scrollable floor selection

### ISSUE THREAD

**Issue by kikelkik** [croxis/Lift#184]
Often, the new scroll-feature with a blank hand on a Lift sign results in nothing but spamming the message `Elevator generator says this floor does not exist. Check shaft for blockage`
Because it doesn't fails ever, it's quite hard to reproduce so I just set up some different Lifts. 
I could determine one reproducable behavior:

1. Create two floors with iron_block at bottom and glass_block on top.
2. Right-click with blank hand on the upper floor sign.
3. Place another glass_block some blocks above the second floor sign.
4. Scroll => Error message received.

I don't know if this quite unrealistic scenario could give you a hint why some Lifts got broke (but they haven't got any other glass blocks above or within the shaft.

Plugin Version: 65
Server Version: git-Paper-385 (Minecraft 1.16.1)

**Comment by croxis** [comment]
If possible can you create a new world with this lift, and attach a zip file of the world?

**Comment by kikelkik** [comment]
I found a better way to reproduce:

1. Right click the sign to select a floor
2. Push the Lift button WITHOUT deactivating the scroll mode 
3. => Error messages spamming until you press again on a Lift sign

The scroll mode should be deactivated when the button is pressed and/or when the player distance to the sign is larger than some blocks (6 blocks should be enough).
Furthermore, a feedback message in chat like "Scrollable floor selection enabled. Click on sign with an item for default mode." and "Scrollable floor selection disabled." might be much more user friendly.

**Comment by TheoRetisch1** [comment]
I'm facing the same problem. The error causes confusion and many complaints.
