### ISSUE TITLE
ERROR - The plugin said to report

### ISSUE THREAD

**Issue by issac4892** [croxis/Lift#187]
[목, 10. 9월 2020 19:25:36 KST INFO] Critical Error. StartfloorDestFloor is null. Please report entire stacktrace plus the following error codes.
[목, 10. 9월 2020 19:25:36 KST INFO] Sign destination: 3
[목, 10. 9월 2020 19:25:36 KST INFO] Floormap: {43=net.croxis.plugins.lift.BukkitFloor@610afd3c, 53=net.croxis.plugins.lift.BukkitFloor@12baa2b5}
[목, 10. 9월 2020 19:25:36 KST INFO] Floormap2: {1=net.croxis.plugins.lift.BukkitFloor@610afd3c, 2=net.croxis.plugins.lift.BukkitFloor@12baa2b5}
[목, 10. 9월 2020 19:25:36 KST INFO] Start y: 53
[목, 10. 9월 2020 19:25:38 KST INFO] Critical Error. StartfloorDestFloor is null. Please report entire stacktrace plus the following error codes.
[목, 10. 9월 2020 19:25:38 KST INFO] Sign destination: 3
[목, 10. 9월 2020 19:25:38 KST INFO] Floormap: {43=net.croxis.plugins.lift.BukkitFloor@71c2392e, 53=net.croxis.plugins.lift.BukkitFloor@761073f4}
[목, 10. 9월 2020 19:25:38 KST INFO] Floormap2: {1=net.croxis.plugins.lift.BukkitFloor@71c2392e, 2=net.croxis.plugins.lift.BukkitFloor@761073f4}
[목, 10. 9월 2020 19:25:38 KST INFO] Start y: 53

**Comment by croxis** [comment]
I'm going to need more info. Pictures or a schematic of the lift.

**Comment by issac4892** [comment]
well... I haven't made a screenshot for this.

2020년 9월 14일 (월) 오전 4:11, croxis <notifications@github.com>님이 작성:

**Comment by issac4892** [comment]
just closing because there was no error from that time
