### ISSUE TITLE
81 percent TPS loss , with last commit

### ISSUE THREAD

**Issue by Tsoccerguy3** [croxis/Lift#189]
There is a big  bug in this  with 1.16.3 paper build 195. /timings report shows a tps loss of 81 percent and the lift plugin dlows the sever down to a crawl. mem leak or wrong API ? IDK

**Comment by kikelkik** [comment]
I fixed these issues with my Pull-Request which is not in the master yet.
If you want that fix now, you can download a self-compiled version from here: https://minecraft-corp.de/downloads/Lift-67.jar

**Comment by Tsoccerguy3** [comment]
I saw this , I pulled you fixes to my local GIT and it works. Thanks

**Comment by kikelkik** [comment]
Cool, so you can close this ticket @Tsoccerguy3

**Comment by croxis** [comment]
Hijacking -- kikelkik, do you want to take over maintaining the plugin? I haven't played minecraft seriously in years.

**Comment by kikelkik** [comment]
Sorry, I felt responsible for this because my changes have been the reason :D

**Comment by Tsoccerguy3** [comment]
croxis , If you are fixing the bug I will close this issue as fixed

**Comment by Tsoccerguy3** [comment]
fixed in pull request from kikelkik . closing

**Comment by croxis** [comment]
kikelik, I was serious

**Comment by kikelkik** [comment]
@croxis You can add me as contributor here on github, spigot and bukkit, so I could help you out without having to create pull requests ^^

**Comment by croxis** [comment]
@kikelkik can you pm me your spigot and bukkit profile names?

**Comment by kikelkik** [comment]
I texted you there. github does'nt support pms
