### ISSUE TITLE
Pls add possibillity to disable mousewheel

### ISSUE THREAD

**Issue by CloudeLecaw** [croxis/Lift#190]
On our server we love the good old way that lift64 was dooing. With lift65 you intoduced the newn mousewheel feature that make it possible to changes lifts with the mouse wheel.

How ever we want that our players use the old way where they clicked onnthe signs to change floors. 

We lookedninnthe config and currently its not possible to disable this mousewheel feature. 

So could you add something in config that allows us to use lift floor signs the old way without the mousewheelnfeature like in life64?

**Comment by croxis** [comment]
I'll add it this weekend

**Comment by croxis** [comment]
Took an extra week, but I did it!
