### ISSUE TITLE
Desactivate lift with boat

### ISSUE THREAD

**Issue by DjeyMute** [croxis/Lift#193]
Hello !

I have a problem with players who get into a boat and then use an elevator that gets them high and so they can't play anymore.

Would it be possible to detect if the player is in a boat before activating the lift ?

Thank you in advance for your reply.

**Comment by kikelkik** [comment]
Hey,
I can't really reproduce your problem: 
![boatinlift](https://user-images.githubusercontent.com/14167723/99157416-e4ddfc00-26c8-11eb-9156-37c8f4dd3d1f.gif)

Could you provide your output with /version and /version Lift?
And could you describe how to reproduce more precisely? Did I do something wrong? (see gif)

**Comment by DjeyMute** [comment]
Hi it's a report by my staff i go to check that.

**Comment by DjeyMute** [comment]
Indeed ... I can't reproduce it either... I go to check with my staff.

**Comment by DjeyMute** [comment]
![2020-11-14_22 41 07](https://user-images.githubusercontent.com/47302852/99157594-8d409000-26ca-11eb-9676-48542402b716.png)
It happens when the boat is blocked by other blocks

**Comment by kikelkik** [comment]
Alright I think thats a circumstance you can prevent by constructing the Lift walls fail safe.
The only solution would be to completely disable Vehicles in Lifts but that would be too much.

**Comment by DjeyMute** [comment]
Yes but the players are not always smart: ')
Yes the best is to do nothing sorry for the inconvenience.

**Comment by kikelkik** [comment]
no worries :)
