### ISSUE TITLE
Compile fails , can not find dependencies

### ISSUE THREAD

**Issue by Tsoccerguy3** [croxis/Lift#197]
During compile it cant find dependencies

G:\Dev\Lift>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< net.croxis.plugins.lift:Lift >--------------------
[INFO] Building Lift 72
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from maven-default-http-blocker: http://0.0.0.0/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] Could not transfer metadata org.spigotmc:spigot-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
[WARNING] org.spigotmc:spigot-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xmlfailed to transfer from http://0.0.0.0/ during a previous attempt. This failure was cached in the local repository and resolution will not be reattempted until the update interval of maven-default-http-blocker has elapsed or updates are forced. Original error: Could not transfer metadata org.spigotmc:spigot-api:1.17.1-R0.1-SNAPSHOT/maven-metadata.xml from/to maven-default-http-blocker (http://0.0.0.0/): transfer failed for http://0.0.0.0/org/spigotmc/spigot-api/1.17.1-R0.1-SNAPSHOT/maven-metadata.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.707 s
[INFO] Finished at: 2021-11-13T20:46:45-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project Lift: Could not resolve dependencies for project net.croxis.plugins.lift:Lift:jar:72: Failed to collect dependencies at org.spongepowered:spongeapi:jar:7.2.0: Failed to read artifact descriptor for org.spongepowered:spongeapi:jar:7.2.0: Could not transfer artifact org.spongepowered:spongeapi:pom:7.2.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [md5-repo (http://repo.md-5.net/content/repositories/releases/, default, releases+snapshots), sponge (http://repo.spongepowered.org/maven, default, releases+snapshots)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by kikelkik** [comment]
You can download the compiled plugin here: https://github.com/croxis/Lift/releases/download/72/Lift-72.jar
